### PR TITLE
Notes and Reorganize project

### PR DESCRIPTION
**Pull request by herrozerro**
Reorganized the project, added notes functionality, updated minor version and prerequisites.

### CODE REVIEW

**Comment by herrozerro** [comment]
Should I target the dev branch?  or is that something you do?

**Comment by herrozerro** [comment]
As far as the issue raised with the auto updater, it probably has to do with the namespace change.  I am sure we could override it to publish to the old name.

**Comment by sander1095** [comment]
I have changed the target branch to `dev`

Could you check if you could get the publishing to work on your branch? I see you have already updateed the minor version so that's good. I don't mind if the name has changed; all we need to do is to make sure the `publish` folder has the correct files in it with the names the program expects. If the publishing works on your branch then we can make sure everything is OK. When we finally merge the stuff to master we can update the `publish` folder so when the updater runs it will retrieve the newest files :)

If you can't get it to work I can go ahead and try it in `dev`. 

A little note: You have made the same mistake as before with your commits. i see you have divided it into 3 commits but the `src/` folder introduction is in the same commit as the one where you add the `Notes` to the character class and thus git does not tell me what changed on a line-per-line basis, but it says the file has been moved and thus it sees all the files as new files. 

For now it's OK, but next time first commit all the code changes and then restructure stuff, it makes it easier to review :)

**Comment by herrozerro** [comment]
A few more changes:
- Recommited character.cs for clarity.
- moved publish folder to the root of the repo.
- modified the publish of the project to a relative path to the above publish path.
- Changed assembly name to keep it the same as previous publishes.
- added version number to title bar.

I tested by installing a previous version and installing it from the new CombatManager.application and it updated.

**Comment by herrozerro** [comment]
- Moved images folder to root for the readme.

**Comment by herrozerro** [comment]
- Updated Overview.png to show the new notes change

**Comment by sander1095** [comment]
Looks good to me!

One final suggestion: I see you added a feature where the version is shown in the title bar. I don't mind it but next time ask/create an issue to see if this is a requested feature before putting effort into it :)

**Comment by sander1095** [comment]
I will merge it into master somewhere this week; I will do some final checks and such.

Thank you for your contribution!

**Pull request merged**
